E2E flow

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -21,18 +21,20 @@ jobs:
       - name: Build Docker Image
         run: docker build -t nishipatil/playwright-tests:latest .
 
-      # Step 4: Push Image to Docker Hub
+      # Step 4: Push Docker Image
       - name: Push Docker Image
         run: docker push nishipatil/playwright-tests:latest
 
       # Step 5: Deploy to EC2 and run container
-      - name: Deploy to EC2 and run tests
+      - name: Deploy to EC2
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_KEY }}
           script: |
+            set -e  # Exit immediately if any command fails
+
             echo "Cleaning old container..."
             sudo docker rm -f playwright-container || true
 
@@ -43,4 +45,4 @@ jobs:
             sudo docker run --name playwright-container nishipatil/playwright-tests:latest
 
             echo "Container logs:"
-            sudo docker logs playwright-container || true
+            sudo docker logs playwright-container
